### PR TITLE
copy-and-comment-operator

### PR DESCRIPTION
**Pull request by Dickby**
Introducing a new operator for copying to kill-ring, commenting and inserting with one action.

### CODE REVIEW

**Comment by redguardtoo** [comment]
could you give me some example? what's some action.

**Comment by Dickby** [comment]
it's an evil-operator, that does the 3 mentioned steps with one operator.
the existing function `evilnc-copy-and-comment-lines` does the same, but i think an evil-operator is more convenient.

**Comment by redguardtoo** [comment]
Thanks. Looks useful.

 Please update the documentation (readme and head of evil-nerd-commenter.el). Then I will merge your code.

**Comment by redguardtoo** [comment]
Thanks. I reviewed the code. There are just a few minor issues to fix before merging.

1, `(let((p (point)))`, a space should exist after `let`

2, could you use `git rebase` to merge your commits into one commit. Here are the steps,

- `git pull -r https://github.com/redguardtoo/evil-nerd-commenter.git master`
- `git rebase -i e1de1d7`, see section `Squashing Commits` from https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History, you only need squash all commits except the first one.
- `git push origin master -f` to force push the commit, the pull request will be automatically updated after your push

**Comment by Dickby** [comment]
I hope it's ok like this.

**Comment by redguardtoo** [comment]
thanks. merged.

**Comment by braham-snyder** [comment]
Any chance you'd want to swap the resulting positions of the commented-out and non-commented-out text? That is, make the operator result in:
```
;; some text
some text
```
Instead of:
```
some text
;; some text
```
`evilnc-copy-and-comment-lines` does the former at the moment, so that could be better for consistency.

**Comment by redguardtoo** [comment]
Yes, I can. I will create a flag, so users could choose the way they prefer

**Comment by redguardtoo** [comment]
01a98a2 users choose the style they prefer when copy and comment (Chen Bin)

CC @Dickby , you may need `(setq evilnc-original-above-comment-when-copy-and-comment t)`

**Comment by Dickby** [comment]
Thanks!

**Pull request merged**
